name: First Workflow
on:
  workflow_dispatch:
    paths:
      - '01-first-action/**'
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print workspace content
        run: ls
      - name: Print goodbye
        run: echo "Done - bye!"
